# This file specifies the parameters of the Cooperative Co-Evolutionary-Based Feature Selection with Random Feature Grouping (CCFSRFG)

[coevolution]
n_subcomps = 4
subpop_sizes = [30, 30, 30, 30]
max_gen = 1000
max_gen_without_improvement = 10
penalty = true
seed = 42
weights = [0.6, 0.4]

[wrapper]
task = "classification"
model_type = "random_forest"
eval_function = "accuracy"

[optimizer]
mut_prob = 0.05
cross_prob = 1.00
sample_perc = 0.50