# This file specifies the parameters of the Cooperative Co-Evolutionary Algorithm with Projection-based Feature Grouping (CCPFG)

[coevolution]
subpop_sizes = [30]
n_subcomps = 4
max_gen = 10000
max_gen_without_improvement = 100

[decomposition]
n_components = 3
method = "clustering"

[wrapper]
task = "classification"
model_type = "k_nearest_neighbors"

[evaluation]
eval_function = "balanced_accuracy"
eval_mode = "kfold_cv"
weights = [0.6, 0.3]

[optimizer]
mutation_rate = 0.05
crossover_rate = 1.00
tournament_sample_size = 1
elite_size = 1