# This file specifies the parameters of the Cooperative Co-Evolutionary Algorithm with Projection-based Feature Grouping (CCPFG)

[coevolution]
subpop_sizes = [30]
n_subcomps = 3
max_gen = 10000
max_gen_without_improvement = 100
seed = 42

[decomposition]
n_components = 2
method = "elitist"
kfolds = 3

[wrapper]
task = "classification"
model_type = "gaussian_naive_bayes"

[evaluation]
eval_function = "balanced_accuracy"
eval_mode = "kfold_cv"
weights = [0.7, 0.3]

[optimizer]
mutation_rate = 0.05
crossover_rate = 1.00
tournament_sample_size = 1
elite_size = 1